[build]
  functions = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-cron"

  [plugins.inputs]
    jobs = [
      { name = "daily-briefs", cron = "0 8 * * *", command = "curl -X POST https://dbg1.netlify.app/.netlify/functions/send-daily-briefs" }
    ]